config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :uff_campus
  resources :campus
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "welcome#index"

  resources :caronas do
    resources :paradas, only: [:create, :destroy]
  end


end

app/models/campu.rb
class Campu < ApplicationRecord
    validates :description, :adress, :number, :neighbourhood, :city, :cep, presence: { message: "não pode estar em branco." }
    validates :number, numericality: { only_integer: true, greater_than: 0, message: "deve ser um número inteiro maior que 0." }
    validates :cep, numericality: { only_integer: true, greater_than: 0, message: "deve ser um número inteiro maior que 0." }
end

app/models/campus.rb
class Campus < ApplicationRecord
    validates :description, :adress, :number, :neighbourhood, :city, :cep, presence: { message: "não pode estar em branco." }
    validates :number, numericality: { only_integer: true, greater_than: 0, message: "deve ser um número inteiro maior que 0." }
    validates :cep, numericality: { only_integer: true, greater_than: 0, message: "deve ser um número inteiro maior que 0." }
  end
  

app/controllers/campus_controller.rb
class CampusController < ApplicationController
  before_action :set_campu, only: %i[ show edit update destroy ]

  # GET /campus or /campus.json
  def index
    @campus = Campu.all
  end

  # GET /campus/1 or /campus/1.json
  def show
  end

  # GET /campus/new
  def new
    @campu = Campu.new
  end

  # GET /campus/1/edit
  def edit
  end

  # POST /campus or /campus.json
  def create
    @campu = Campu.new(campu_params)

    respond_to do |format|
      if @campu.save
        format.html { redirect_to campu_url(@campu), notice: "Campu was successfully created." }
        format.json { render :show, status: :created, location: @campu }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @campu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campus/1 or /campus/1.json
  def update
    respond_to do |format|
      if @campu.update(campu_params)
        format.html { redirect_to campu_url(@campu), notice: "Campu was successfully updated." }
        format.json { render :show, status: :ok, location: @campu }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @campu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campus/1 or /campus/1.json
  def destroy
    @campu.destroy

    respond_to do |format|
      format.html { redirect_to campus_url, notice: "Campu was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campu
      @campu = Campu.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def campu_params
      params.require(:campu).permit(:description, :adress, :number, :neighbourhood, :city, :cep, :deactivationDate)
    end
end

app/helpers/campus_helper.rb
module CampusHelper
end

app/views/campus/_campu.html.erb
<div id="<%= dom_id campu %>" class="text-center">
  <p class="lead">
    <strong>Nome: </strong>
    <%= campu.description %>
  </p>

  <p class="lead">
    <strong>Endereço: </strong>
    <%= campu.adress %>
  </p>

  <p class="lead">
    <strong>Número: </strong>
    <%= campu.number %>
  </p>

  <p class="lead">
    <strong>Bairro: </strong>
    <%= campu.neighbourhood %>
  </p>

  <p class="lead">
    <strong>Cidade: </strong>
    <%= campu.city %>
  </p>

  <p class="lead">
    <strong>Cep:</strong>
    <%= campu.cep %>
  </p>

  <p class="lead">
    <% if campu.deactivationDate %>
      <strong>O campus foi desativado em: </strong>
      <%= campu.deactivationDate %>
    <% else %>
      <strong>O campus está ativo</strong>
    <% end %>
  </p>
</div>
</div>

app/views/campus/_form.html.erb
<%= form_with(model: campu, class: "d-flex flex-column justify-content-center") do |form| %>
  <% if campu.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(campu.errors.count, "error") %> prohibited this campu from being saved:</h2>

      <ul>
        <% campu.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group p-2">
    <%= form.label :nome, class: "text-center", style: "display: block" %>
    <%= form.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group p-2">
    <%= form.label :endereço, class: "text-center", style: "display: block" %>
    <%= form.text_field :adress, class: "form-control" %>
  </div>

  <div class="form-group p-2">
    <%= form.label :número, class: "text-center", style: "display: block" %>
    <%= form.number_field :number, class: "form-control" %>
  </div>

  <div class="form-group p-2">
    <%= form.label :bairro, class: "text-center", style: "display: block" %>
    <%= form.text_field :neighbourhood, class: "form-control" %>
  </div>

  <div class="form-group p-2">
    <%= form.label :cidade, class: "text-center", style: "display: block" %>
    <%= form.text_field :city, class: "form-control" %>
  </div>

  <div class="form-group p-2">
    <%= form.label :CEP, class: "text-center", style: "display: block" %>
    <%= form.number_field :cep, class: "form-control" %>
  </div>

  <div class="form-group p-2">
    <%= form.label :Desativação, class: "text-center", style: "display: block" %>
    <%= form.date_field :deactivationDate, class: "form-control" %>
  </div>

  <div class="form-group text-center mt-4">
    <%= form.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/campus/edit.html.erb
<!-- Bootstrap needys -->
<%= stylesheet_link_tag "bootstrap.css" %>
<% if notice %>
  <div class="notice d-flex justify-content-center align-items-center m-5">
    <%= notice %>
  </div>
<% end %>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h1 class="text-center mb-4">Editando campus</h1>
      <%= render "form", campu: @campu %>
      <div class="text-center mt-4">
        <%= link_to "Mostrar este Campus", @campu, class: "btn btn-secondary mr-2" %>
        <%= link_to "Voltar à lista de Campus", campus_path, class: "btn btn-primary mt-2" %>
      </div>
    </div>
  </div>
</div>

app/views/campus/index.html.erb
<!-- Bootstrap needys -->
<%= stylesheet_link_tag "bootstrap.css" %>
<div class="container">
  <h1 class="text-center mb-5">Campus da UFF</h1>

  <div class="row justify-content-center">
    <div class="table-responsive">
      <div class="row">
        <% @campus.each do |campu| %>
          <div class="col-md-4">
            <div class="card mb-4 bg-secondary text-secondary-emphasys">
              <div class="card-body">
                <h5 class="card-title"><%= campu.description %></h5>
                <p class="card-text"><strong>Endereço:</strong> <%= campu.adress %>, <%= campu.number %>, <%= campu.city %></p>
                <p class="card-text"><strong>CEP:</strong> <%= campu.cep %></p>
                <p class="card-text"><strong>Foi desativado? </strong> <%= campu.deactivationDate.nil? ? 'Não' : 'Sim' %></p>
                <div class="button-group">
                  <%= link_to 'Mostrar', campu, class: "btn btn-primary mr-2 mt-3" %>
                  <%= link_to 'Editar', edit_campu_path(campu), class: "btn btn-secondary mr-2 mt-3"%>
                  <%= button_to 'Excluir', carona_path(campu), method: :delete, data: { confirm: 'Tem certeza?' }, class: "btn btn-danger mr-2 mt-3" %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  </div>
    </div>
  </div>
  <div class="row justify-content-center mt-5">
    <div class="col-md-4">
      <%= link_to 'Novo Campus', new_campu_path, class: "btn btn-success btn-block" %>
    </div>
  </div>
</div>

app/views/campus/new.html.erb
<!-- Bootstrap needys -->
<%= stylesheet_link_tag "bootstrap.css" %>
<% if notice %>
  <div class="notice d-flex justify-content-center align-items-center m-5">
    <%= notice %>
  </div>
<% end %>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h1 class="text-center">Criar novo campus</h1>
      <%= render "form", campu: @campu %>
    </div>
    <div class="text-center">
      <%= link_to "Voltar à lista de campus", campus_path, class: "btn btn-primary mt-3" %>
    </div>
  </div>
</div>  

app/views/campus/show.html.erb
<!-- Bootstrap needys -->
<%= stylesheet_link_tag "bootstrap.css" %>

<div class="container">
  <div class="bg-text p-3">
    <p class="text-success"><%= notice %></p>
      <div class="card p-3">
        <%= render @campu %>
        <div class="text-center mt-3">
          <%= link_to "Editar este campus", edit_campu_path(@campu), class: "btn btn-primary mr-2 mr-3" %>
          <%= link_to "Voltar à lista de campus", campus_path, class: "btn btn-secondary" %>          
          <%= button_to "Destruir este campus", @campu, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger mt-3" %>
        </div>
      </div>
    </div> 
  </div> 
</div>