config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :uff_campus
  resources :campus
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "welcome#index"

  resources :caronas do
    resources :paradas, only: [:create, :destroy]
  end


end

app/models/uff_campus.rb
class UffCampus < ApplicationRecord
    validates :description, presence: { message: "O campo 'description' não pode estar em branco." }
    validates :adress, presence: { message: "O campo 'adress' não pode estar em branco." }
    validates :number, presence: { message: "O campo 'number' não pode estar em branco." },
                        numericality: { only_integer: true, greater_than: 0, message: "O campo 'number' deve ser um número inteiro maior que 0." }
    validates :neighbourhood, presence: { message: "O campo 'neighbourhood' não pode estar em branco." }
    validates :city, presence: { message: "O campo 'city' não pode estar em branco." }
    validates :cep, presence: { message: "O campo 'cep' não pode estar em branco." },
                    numericality: { only_integer: true, greater_than: 0, message: "O campo 'cep' deve ser um número inteiro maior que 0." }      
end

app/controllers/uff_campus_controller.rb
class UffCampusController < ApplicationController
  before_action :set_uff_campu, only: %i[ show edit update destroy ]

  # GET /uff_campus or /uff_campus.json
  def index
    @uff_campus = UffCampus.all
  end

  # GET /uff_campus/1 or /uff_campus/1.json
  def show
  end

  # GET /uff_campus/new
  def new
    @uff_campu = UffCampus.new
  end

  # GET /uff_campus/1/edit
  def edit
  end

  # POST /uff_campus or /uff_campus.json
  def create
    @uff_campu = UffCampus.new(uff_campu_params)

    respond_to do |format|
      if @uff_campu.save
        format.html { redirect_to uff_campu_url(@uff_campu), notice: "Uff campus was successfully created." }
        format.json { render :show, status: :created, location: @uff_campu }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @uff_campu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /uff_campus/1 or /uff_campus/1.json
  def update
    respond_to do |format|
      if @uff_campu.update(uff_campu_params)
        format.html { redirect_to uff_campu_url(@uff_campu), notice: "Uff campus was successfully updated." }
        format.json { render :show, status: :ok, location: @uff_campu }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @uff_campu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uff_campus/1 or /uff_campus/1.json
  def destroy
    @uff_campu.destroy

    respond_to do |format|
      format.html { redirect_to uff_campus_index_url, notice: "Uff campus was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_uff_campu
      @uff_campu = UffCampus.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def uff_campu_params
      params.require(:uff_campu).permit(:description, :adress, :number, :neighbourhood, :city, :cep, :deactivationDate)
    end
end

app/helpers/uff_campus_helper.rb
module UffCampusHelper
end

app/views/uff_campus/_form.html.erb
<%= form_with(model: uff_campu) do |form| %>
  <% if uff_campu.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(uff_campu.errors.count, "error") %> prohibited this uff_campu from being saved:</h2>

      <ul>
        <% uff_campu.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :adress, style: "display: block" %>
    <%= form.text_field :adress %>
  </div>

  <div>
    <%= form.label :number, style: "display: block" %>
    <%= form.number_field :number %>
  </div>

  <div>
    <%= form.label :neighbourhood, style: "display: block" %>
    <%= form.text_field :neighbourhood %>
  </div>

  <div>
    <%= form.label :city, style: "display: block" %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.label :cep, style: "display: block" %>
    <%= form.number_field :cep %>
  </div>

  <div>
    <%= form.label :deactivationDate, style: "display: block" %>
    <%= form.date_field :deactivationDate %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/uff_campus/_uff_campus.html.erb
<div id="<%= dom_id uff_campus %>">
  <p>
    <strong>Description:</strong>
    <%= uff_campus.description %>
  </p>

  <p>
    <strong>Adress:</strong>
    <%= uff_campus.adress %>
  </p>

  <p>
    <strong>Number:</strong>
    <%= uff_campus.number %>
  </p>

  <p>
    <strong>Neighbourhood:</strong>
    <%= uff_campus.neighbourhood %>
  </p>

  <p>
    <strong>City:</strong>
    <%= uff_campus.city %>
  </p>

  <p>
    <strong>Cep:</strong>
    <%= uff_campus.cep %>
  </p>

  <p>
    <strong>Deactivationdate:</strong>
    <%= uff_campus.deactivationDate %>
  </p>

</div>

app/views/uff_campus/edit.html.erb
<h1>Editing uff campus</h1>

<%= render "form", uff_campu: @uff_campu %>

<br>

<div>
  <%= link_to "Show this uff campus", @uff_campu %> |
  <%= link_to "Back to uff campus", uff_campus_index_path %>
</div>

app/views/uff_campus/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Uff campus</h1>

<div id="uff_campus">
  <% @uff_campus.each do |uff_campu| %>
    <%= render uff_campu %>
    <p>
      <%= link_to "Show this uff campus", uff_campu %>
    </p>
  <% end %>
</div>

<%= link_to "New uff campus", new_uff_campu_path %>

app/views/uff_campus/new.html.erb
<h1>New uff campus</h1>

<%= render "form", uff_campu: @uff_campu %>

<br>

<div>
  <%= link_to "Back to uff campus", uff_campus_index_path %>
</div>

app/views/uff_campus/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @uff_campu %>

<div>
  <%= link_to "Edit this uff campus", edit_uff_campu_path(@uff_campu) %> |
  <%= link_to "Back to uff campus", uff_campus_index_path %>

  <%= button_to "Destroy this uff campus", @uff_campu, method: :delete %>
</div>