config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :uff_campus
  resources :campus
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "welcome#index"

  resources :caronas do
    resources :paradas, only: [:create, :destroy]
  end


end

app/models/carona.rb
class Carona < ApplicationRecord
    has_many :paradas, dependent: :destroy
  
    validates :motorista, :inicio, :fim, :data, :hora, presence: { message: "não pode estar em branco." }
    validates :numero_de_passageiros, presence: { message: "não pode estar em branco." },
                                     numericality: { only_integer: true, greater_than: 0, message: "deve ser um número inteiro maior que 0." }
    validates :custo, presence: { message: "não pode estar em branco." },
                     numericality: { greater_than_or_equal_to: 0, message: "deve ser um número maior ou igual a 0." }
  end
  

app/controllers/caronas_controller.rb
class CaronasController < ApplicationController
  before_action :set_carona, only: [:show, :edit, :update, :destroy]

  def index
    @caronas = Carona.all
  end

  def show
    @paradas = @carona.paradas
  end

  def new
    @carona = Carona.new
  end
  
  def create
    @carona = Carona.new(carona_params)

    if !Campus.pluck(:description).include?(@carona.inicio) && !Campus.pluck(:description).include?(@carona.fim)
      flash[:error] = 'Carona inválida. O ponto de partida ou de chegada devem ser um campus da UFF'
      render :new
    elsif @carona.save
      redirect_to @carona, notice: 'Carona was successfully created.'
    else
      flash[:error] = @carona.errors.full_messages.join(", ")
      render :new
    end
  end

  def edit
  end

  def update
    if !Campus.pluck(:description).include?(params[:carona][:inicio]) && !Campus.pluck(:description).include?(params[:carona][:fim])
      redirect_to edit_carona_path(@carona), notice: 'Carona inválida. O ponto de partida ou de chegada devem ser um campus da UFF'
    elsif @carona.update(carona_params)
      redirect_to @carona, notice: 'A carona foi atualizada.'
    else
      flash[:error] = @carona.errors.full_messages.join(", ")
      render :edit
    end
  end

  def destroy
    @carona.destroy
    redirect_to caronas_url, notice: 'Carona excluída com sucesso.'
  end

  private

  def set_carona
    @carona = Carona.find(params[:id])
  end

  def carona_params
    params.require(:carona).permit(:motorista, :data, :hora, :numero_de_passageiros, :custo, :inicio, :fim, :observacao)
  end
end

app/helpers/caronas_helper.rb
module CaronasHelper
end

app/views/caronas/_form.html.erb
<%= form_with(model: carona, class: "d-flex flex-column justify-content-center") do |form| %>
  <% if carona.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(carona.errors.count, "error") %> prohibited this campu from being saved:</h2>

      <ul>
        <% carona.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>   


  <% campus = Campus.pluck(:description) %>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group p-2">
        <%= form.label :motorista, class: "text-center", style: "display: block" %>
        <%= form.text_field :motorista, class: "form-control" %>
      </div>
      <div class="form-group p-2">
        <%= form.label :data, class: "text-center", style: "display: block" %>
        <%= form.date_field :data, class: "form-control", value: Time.now.strftime('%Y-%m-%d') %>
      </div>
      <div class="form-group p-2">
        <%= form.label :hora, class: "text-center", style: "display: block" %>
        <%= form.time_field :hora, class: "form-control", value: Time.now.strftime('%H:%M') %>
      </div>
      <div class="form-group p-2">
        <%= form.label :numero_de_passageiros, class: "text-center", style: "display: block" %>
        <%= form.text_field :numero_de_passageiros, class: "form-control" %>
      </div>
      
    </div>
    <div class="col-md-6">
    
      <div class="form-group p-2">
        <%= form.label :custo, class: "text-center", style: "display: block" %>
        <%= form.text_field :custo, class: "form-control" %>
      </div>
      <div class="form-group p-2" style="display:block">
        <%= form.label :inicio, class: "text-center", style: "display: block" %>
        <%= form.text_field :inicio, class: "form-control" %>
      </div>
      
      <div class="form-group p-2">
        <%= form.label :fim, class: "text-center", style: "display: block" %>
       <%= form.text_field :fim, class: "form-control" %>
      </div>
        
      <div class="form-group p-2">
        <%= form.label :observacao, class: "text-center", style: "display: block" %>
        <div class="">
          <%= form.text_area :observacao, class: "form-control" %>
        </div>
      </div>

    </div>

  </div>

  <div class="form-group p-2 d-flex justify-content-center m-5">
    <!-- Change the type of the button to "submit" -->
    <%= form.button "Concluir", type: "submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/caronas/edit.html.erb
<!-- app/views/caronas/edit.html.erb -->
<%= stylesheet_link_tag "bootstrap.css" %>
<% if notice %>
        <div class="notice d-flex justify-content-center align-items-center m-5">
                <%= notice %>
        </div>
<% end %>
<div class="d-flex justify-content-center align-items-center">
        
        <div class="center-content">
                <%= render 'form', carona: @carona do %>
                <% end %>
        </div>
        <div>

        <div class="d-flex justify-content-center align-items-center center-content">
                <div class="d-flex justify-content-center center-content align-items-center flex-column">
                        <h2 class="m-4">Paradas</h2>
                        <% if @carona.paradas.any? %>
                                <div class="paradas">
                                        <% @carona.paradas.each do |parada| %>
                                                <div class="parada form-group p-2 d-flex justify-content-center align-items-center">
                                                        <div><%= parada.local %></div>
                                                        <div>
                                                                <%= button_to 'Remover', [@carona, parada], method: :delete, data: { confirm: 'Tem certeza que deseja remover esta parada?' }, class: 'btn btn-danger', :form => { :action => carona_path(@carona), :method => :get } %>
                                                        </div>
                                                </div>
                                        <% end %>
                                </div>
                        <% else %>
                                <p>Nenhuma parada encontrada.</p>
                        <% end %>
                </div>
        </div>

                <h2>Adicionar Parada</h2>
                <%= form_for([@carona, Parada.new]) do |f| %>
                        <div class="form-group p-2">
                                <%= f.label :local, class: "text-center" %>
                                <%= f.text_field :local, class: "form-control"%>
                        </div>


                        <div class="form-group p-2 d-flex justify-content-center m-5">
                                <%= f.submit 'Adicionar Parada', class: 'btn btn-primary' %>
                        </div>
                <% end %>
                </div>
        </div>        
</div>  
<div class="d-flex justify-content-center">
        <div class="form-group">
                <%= link_to 'Visualizar', @carona, class: 'btn btn-primary' %>
                <%= link_to 'Voltar para Listagem', caronas_path, class: 'btn btn-secondary' %>
        </div>
</div>

app/views/caronas/index.html.erb
<!-- Bootstrap needys -->
<%= stylesheet_link_tag "bootstrap.css" %>
<div class="container">
  <h1 class="text-center mb-5">Caronas</h1>

  <div class="row justify-content-center">
    <div class="table-responsive">
      <div class="row">
        <% @caronas.each do |carona| %>
          <div class="col-md-4">
            <div class="card mb-4 bg-secondary text-secondary-emphasys">
              <div class="card-body">
                <h5 class="card-title"> <%= carona.motorista == "" ? 'Motorista não alocado' :  'Carona do ' + carona.motorista %></h5>
                <p class="card-text"><strong>Início:</strong> <%= carona.inicio == "" ? 'Início indisponível' : "#{carona.inicio}" %></p>
                <p class="card-text"><strong>Fim:</strong> <%= carona.fim == "" ? 'Fim indisponível' : "#{carona.fim}" %></p>
                <p class="card-text"><strong>Hora:</strong> <%= carona.hora.nil? ? 'Hora indisponível' : "#{carona.hora.strftime("%H:%M")}" %> </p>
                <p class="card-text"><strong>Custo:</strong> <%= carona.custo.nil? ? 'Gratuita' : "#{carona.custo}" %></p>
                <div class="button-group">
                  <%= link_to 'Mostrar', carona, class: "btn btn-primary mr-2 mt-3" %>
                  <%= link_to 'Editar', edit_carona_path(carona), class: "btn btn-secondary mr-2 mt-3" %>
                  <%= button_to 'Excluir', carona_path(carona), method: :delete, data: { confirm: 'Tem certeza?' }, class: "btn btn-danger mr-2 mt-3" %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
    </div>
  </div>
  <div class="row justify-content-center mt-5">
    <div class="col-md-4">
      <%= link_to 'Nova Carona', new_carona_path, class: "btn btn-success btn-block" %>
    </div>
  </div>
</div>

app/views/caronas/new.html.erb
<!-- app/views/caronas/new.html.erb -->
<%= stylesheet_link_tag "bootstrap.css" %>
<% if notice %>
        <div class="notice d-flex justify-content-center align-items-center m-5">
                <%= notice %>
        </div>
<% end %>
<div class="container">
    <h1>Nova Carona</h1>
    <%= render "form", carona:@carona %>
    <div class="text-center">
        <%= link_to 'Voltar para Listagem', caronas_path, class: "btn btn-secondary" %>
    </div>
</div>

app/views/caronas/show.html.erb
<!-- FILEPATH: /home/kalyter/Projects/STI-Trainee-Process (cópia)/app/views/caronas/show.html.erb -->
<%= stylesheet_link_tag "bootstrap.css" %>

<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="card">
                <div class="card-header">
                    <h1>Detalhes da carona</h1>
                </div>
                <div class="card-body">

                    <h5 class="card-title"> <%= @carona.motorista == "" ? 'Motorista não alocado' :  'Carona do ' + @carona.motorista %></h5>
                    <p class="card-text"><strong>Início:</strong> <%= @carona.inicio == "" ? 'Início indisponível' : "#{@carona.inicio}" %></p>
                    <p class="card-text"><strong>Fim:</strong> <%= @carona.fim == "" ? 'Fim indisponível' : "#{@carona.fim}" %></p>
                    <p class="card-text"><strong>Data :</strong> <%= @carona.data.nil? ? 'Data indisponível' : "#{@carona.data}" %></p>
                    <p class="card-text"><strong>Hora:</strong> <%= @carona.hora.nil? ? 'Hora indisponível' : "#{@carona.hora.strftime("%H:%M")}" %> </p>
                    <p class="card-text"><strong>Custo:</strong> <%= @carona.custo.nil? ? 'Gratuita' : "#{@carona.custo}" %></p>
                    <p class="card-text"><strong>Número de passageiros:</strong> <%= @carona.numero_de_passageiros.nil? ? 'Número de passageiros não definido' : "#{@carona.numero_de_passageiros}" %></p>
                    <p class="card-text"><strong>Observação:</strong> <%= @carona.observacao == "" ? 'A carona não possui observações' : "#{@carona.observacao}" %></p>
                    <div class="d-flex justify-content-center align-items-center center-content">
                    <div class="d-flex justify-content-center center-content align-items-center flex-column">
                    <% if @carona.paradas.any? %>
                        <h2 class="m-4">Paradas</h2>
                        <div class="paradas">
                        <% @carona.paradas.each do |parada| %>
                            <div class="parada form-group p-2 d-flex justify-content-center align-items-center">
                                <div><%= parada.local %></div>
                            </div>
                        <% end %>
                        </div>
                        <% else %>
                            <h3 class="m-4">A carona não tem nenhuma parada.</h3>
                        <% end %>
                    </div>
                </div>
                </div>
                <div class="card-footer d-flex justify-content-between mx-auto text-center">
                    <%= link_to 'Editar', edit_carona_path(@carona), class: 'btn btn-primary' %>
                    <%= link_to 'Voltar', caronas_path, class: 'btn btn-secondary' %>
                    <%= button_to 'Excluir', carona_path(@carona), method: :delete, data: { confirm: 'Tem certeza?' }, class: "btn btn-secondary" %>
                </div>
            </div>
        </div>
    </div>
</div>